const Chevron = () => {
    return (
        <>
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>{' '}
            <div className="left-chevron"></div>
            <div className="left-chevron"></div>
        </>
    );
};
export default Chevron;
